stages:
- name: graylog-deploy
  steps:
  - applyYamlConfig:
      path: ./graylog.yaml
timeout: 60
notification:
  recipients:
  - recipient: team-infra
    notifier: c-75kcc:n-wpjss
  condition:
  - Success
  - Changed
  - Failed
