apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"name":"elasticsearch","namespace":"graylog"},"spec":{"replicas":1,"selector":{"matchLabels":{"service":"elasticsearch"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"service":"elasticsearch"}},"spec":{"containers":[{"args":["elasticsearch","-Des.cluster.name=graylog"],"image":"elasticsearch:2","name":"elasticsearch","resources":{},"volumeMounts":[{"mountPath":"/usr/share/elasticsearch/data","name":"elasticsearch-volume"}]}],"restartPolicy":"Always","volumes":[{"name":"elasticsearch-volume","persistentVolumeClaim":{"claimName":"elasticsearch-pvc"}}]}}},"status":{}}
  creationTimestamp: "2021-04-09T16:57:33Z"
  generation: 1
  name: elasticsearch
  namespace: graylog
  resourceVersion: "7953"
  selfLink: /apis/apps/v1/namespaces/graylog/deployments/elasticsearch
  uid: 69fcf15d-8f40-439a-8233-49eac050e0fa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Des.cluster.name=graylog
        image: elasticsearch:2
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: elasticsearch-volume
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-09T16:58:04Z"
    lastUpdateTime: "2021-04-09T16:58:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-09T16:57:33Z"
    lastUpdateTime: "2021-04-09T16:58:04Z"
    message: ReplicaSet "elasticsearch-77c59579b6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
