apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"graylog-pvc","namespace":"graylog"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"6Gi"}},"storageClassName":"longhorn"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2021-04-09T17:22:31Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: graylog-pvc
  namespace: graylog
  resourceVersion: "16356"
  selfLink: /api/v1/namespaces/graylog/persistentvolumeclaims/graylog-pvc
  uid: d43ef568-4260-42c7-b814-fc26770e99c9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-d43ef568-4260-42c7-b814-fc26770e99c9
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 6Gi
  phase: Bound
